name: rabbit
keybinds:
  compile: "!c"
  launch: "!`"
  iterate: "!v"
  pc_close_loop: "!+v"

paths:
  trenchbroom: I:\Quake\TrenchBroom-Win64-v2024.1-Release
  trenchbroom_preferences: C:\Users\Rabbit\AppData\Roaming\TrenchBroom\Preferences.json
  ericw: I:\Quake\ericw
  engine_exes:
    - I:\Quake\Game\engines\quakespasm.exe
    - I:\Quake\Game\engines\ironwail.exe
  configs: I:\Quake\cfg
  maps: I:\Quake\Dev\maps

cfg_whitelist:
  remobilize.cfg:
    - remobilize_test15

# search through key-value pairs per entity
dependencies:
  # sound effects
  - name: SOUND_EFFECTS
    destination: sound
    eval: "[value for key, value in entity.kv.items() if value.endswith('.wav')]"
  # models
  - name: MODELS
    destination: "*"
    eval: "[value for key, value in entity.kv.items() if value.endswith('.mdl')]"
  # skyboxes
  - name: SKYBOXES
    destination: gfx/env
    eval: "entity.kv.get('sky')"
  # music
  - name: MUSIC
    destination: music
    exec: |
      if entity.kv['classname'] in ['worldspawn, misc_changemusic']:
        output = entity.kv.get('sounds')

jampack:
  deny:
    - regex: 'autosave..+\.\d+\.map'
    - path: "*.prt"
    - path: "*.log"
    - path: "*.texinfo.json"
  allow:
    - patterns:
        - path: "*.map"
      destination: mapsrc
    - patterns:
        - path: descript.ion
        - path: "*.def"
        - path: "*.fgd"
        - path: "*.json"
        - path: "*.pak"
        - path: "*.dat"
        - path: "*.rc"
      destination: .
    - patterns:
        - path: "*.txt"
        - path: "*.html"
        - path: "*.md"
        - path: readme/*
      destination: readme
    - patterns:
        - path: "*.bsp"
        - path: "*.lit"
      destination: maps

submit:
  allowed:
    - mapsrc/*.map
    - sound/**/*.wav
    - music/*
    - track*.*
    - maps/*.bsp
    - maps/*.lit
    - gfx/env/*.tga
    - gfx/env/**/*.tga
    - readme/*
    - progs/**/*.mdl

template:
  folders:
    - maps
    - mapsrc
    - music
    - gfx/env/{name}
    - sound/{name}
    - progs/{name}
    - readme
    - build
  copy:
    - files:
        - assets\template.map
        - assets/todo.md
      destination: .
    - files:
        - assets/readme.md
      destination: readme

ericw:
  bsp: maps
  src: mapsrc
  profiles:
    - name: dev
      qbsp:
        - -bsp2
        - -verbose
      vis:
        - -fast
        - -vv
      light:
        - -dirtdebug
    - name: submit
      qbsp:
        - -leaktest
        - -bsp2
        - -splitturb
      vis:
        - -noambient
      light:
        - -extra4

symlink:
  - target: gfx/env/{name}
    destination: gfx/env
  - target: sound/{name}
    destination: sound
  - target: maps/*.bsp
    destination: maps
  - target: maps/*.lit
    destination: maps
  - target: music/track*.*
    destination: music
