# some values can be lists [] or strings '', ""
# in the case of ericw, it can be a folder containing different versions...
# ericw = ['I:\Quake\ericw\ericw-tools-2.0.0-alpha7-win64', 'I:\Quake\ericw\ericw-tools-v0.18.1-32-g6660c5f-win64']
# ...or just a string of a folder path containing those folders...
# ericw = 'I:\Quake\ericw'

# templates will be generated like: gfx/env/{name} = gfx/env/rabbit
name = 'rabbit'

[keybinds]
# use AHK notation
# https://www.autohotkey.com/docs/v2/Hotkeys.htm#Symbols
# https://www.autohotkey.com/docs/v2/KeyList.htm
compile = '!c'
launch = '!`'
iterate = '!v'
pc_close_loop = '!+v'

[paths]
trenchbroom = 'I:\Quake\TrenchBroom-Win64-v2024.1-Release'
trenchbroom_preferences = 'C:\Users\Rabbit\AppData\Roaming\TrenchBroom\Preferences.json'

# can be list or string
ericw = 'I:\Quake\ericw'

# can be list or string
engine_exes = [
	'I:\Quake\Game\quakespasm-0.95.0_win64\quakespasm.exe',
	'I:\Quake\Game\quakespasm-0.95.0_win64\ironwail.exe',
]
configs = 'I:\Quake\cfg'
maps = 'I:\Quake\Dev\maps'

[cfg_whitelist]
'remobilize.cfg' = ['remobilize_test15']

[jampack]
folder_to_pak = 'pakme'
# i think below is obsolete ?
# parents = [
# 	'readme',
# 	'sound',
# 	'gfx/env',
# 	'music',
# 	'maps',
# 	'map',
# 	'mapsrc',
# 	'progs',
# 	'models',
# ]

# for dependencies read from the bsp
[[jampack.dependencies]]
value_patterns = ['*.wav']
destination = 'sound'

[[jampack.dependencies]]
value_patterns = ['*.mdl']

[[jampack.dependencies]]
keys = ['sky']
stem_append = '*.tga'
destination = 'gfx/env'

[[jampack.dependencies]]
classnames = ['misc_changemusic', 'worldspawn']
keys = ['sounds']
stem_prepend = 'track'
destination = 'music'
# stem_append = '.*'
# value_regexs = ['track\d+\..+']

# for grabbing non-dependant files, like readme files or .map files
[[jampack.allow]]
patterns = [
	'descript.ion',
	'*.def',
	'*.fgd',
	'*.json',
	'*.pak',
	'*.dat',
	'*.rc',
]
destination = '.'

[[jampack.allow]]
patterns = ['*.map']
except_patterns = ['autosave/*.map']
except_regexs = ['autosave..+\.\d+\.map']
destination = 'mapsrc'

[[jampack.allow]]
patterns = ['*.bsp', '*.lit']
destination = 'maps'

[[jampack.allow]]
patterns = ['*.txt', '*.html', '*.md', 'readme/*']
destination = 'readme'


[submit]
allowed = [
	'mapsrc/*.map',
	'sound/**/*.wav',
	'music/*',
	'maps/*.bsp',
	'maps/*.lit',
	'gfx/env/**/*.tga',
	'readme/*',
	'progs/**/*.mdl',
]

[template]
folders = [
	'maps',
	'mapsrc',
	'music',
	'gfx/env/{name}',
	'sound/{name}',
	'progs/{name}',
	'readme',
	'build',
]

[[template.copy]]
files = ['assets\template.map', 'assets/todo.md']
destination = '.'

[ericw]
bsp = 'maps'
src = 'mapsrc'

[[ericw.profiles]]
name = 'dev'
qbsp = ['-bsp2', '-verbose']
vis = ['-fast', '-vv']
light = ['-dirtdebug']

[[ericw.profiles]]
name = 'submit'
qbsp = ['-leaktest', '-bsp2', '-splitturb']
vis = ['-noambient']
light = ['-extra4']
