name: rabbit
keybinds:
  compile: "!c"
  launch: "!`"
  iterate: "!v"
  pc_close_loop: "!+v"

paths:
  trenchbroom: I:\Quake\TrenchBroom-Win64-v2024.1-Release
  trenchbroom_preferences: C:\Users\Rabbit\AppData\Roaming\TrenchBroom\Preferences.json
  ericw: I:\Quake\ericw
  engine_exes:
    - I:\Quake\Game\engines\quakespasm.exe
    - I:\Quake\Game\engines\ironwail.exe
  configs: I:\Quake\cfg
  maps: I:\Quake\Dev\maps

cfg_whitelist:
  remobilize.cfg:
    - remobilize_test15

dependencies:
  # sound effects
  - which: value
    condition: endswith
    what: .wav
    destination: sound
  # models
  - which: value
    condition: endswith
    what: .mdl
    destination: null
  # skyboxes
  - which: key
    condition: equals
    what: sky
    destination: gfx/env
  # music
  - pattern_type: and
    patterns:
      - which: key
        condition: equals
        what: sounds
      - condition: entity_has_patterns
        pattern_type: and
        patterns:
          - which: key
            condition: equals
            what: classname
          - which: value
            condition: equals
            what: [worldspawn, misc_changemusic]
    destination: gfx/env

jampack:
  folder_to_pak: pakme
  allow:
    - patterns:
        - descript.ion
        - "*.def"
        - "*.fgd"
        - "*.json"
        - "*.pak"
        - "*.dat"
        - "*.rc"
      destination: .
    - patterns:
        - "*.map"
      except_patterns:
        - autosave/*.map
      except_regexs:
        - autosave..+\.\d+\.map
      destination: mapsrc
    - patterns:
        - "*.bsp"
        - "*.lit"
      destination: maps
    - patterns:
        - "*.txt"
        - "*.html"
        - "*.md"
        - readme/*
      destination: readme

submit:
  allowed:
    - mapsrc/*.map
    - sound/**/*.wav
    - music/*
    - track*.*
    - maps/*.bsp
    - maps/*.lit
    - gfx/env/*.tga
    - gfx/env/**/*.tga
    - readme/*
    - progs/**/*.mdl

template:
  folders:
    - maps
    - mapsrc
    - music
    - gfx/env/{name}
    - sound/{name}
    - progs/{name}
    - readme
    - build
  copy:
    - files:
        - assets\template.map
        - assets/todo.md
      destination: .

ericw:
  bsp: maps
  src: mapsrc
  profiles:
    - name: dev
      qbsp:
        - -bsp2
        - -verbose
      vis:
        - -fast
        - -vv
      light:
        - -dirtdebug
    - name: submit
      qbsp:
        - -leaktest
        - -bsp2
        - -splitturb
      vis:
        - -noambient
      light:
        - -extra4
