# some values can be lists [] or strings '', ""
# in the case of ericw, it can be a folder containing different versions...
# ericw = ['I:\Quake\ericw\ericw-tools-2.0.0-alpha7-win64', 'I:\Quake\ericw\ericw-tools-v0.18.1-32-g6660c5f-win64']
# ...or just a string of a folder path containing those folders...
# ericw = 'I:\Quake\ericw'

# used for map names and {name}
# ex: if your name is rabbit, maps will be zipped as ej3_rabbit
# and templates will be generated like gfx/env/rabbit/
name = 'rabbit'

[keybinds]
# use AHK notation
# https://www.autohotkey.com/docs/v2/Hotkeys.htm#Symbols
# https://www.autohotkey.com/docs/v2/KeyList.htm
compile = '!c'
launch = '!`'
iterate = '!v'
pc_close_loop = '!+v'

[paths]
trenchbroom = 'I:\Quake\TrenchBroom-Win64-v2024.1-Release'
trenchbroom_preferences = 'C:\Users\Rabbit\AppData\Roaming\TrenchBroom\Preferences.json'

# can be list or string
ericw = 'I:\Quake\ericw'

# can be list or string
engine_exes = [
	'I:\Quake\Game\quakespasm-0.95.0_win64\quakespasm.exe',
	'I:\Quake\Game\quakespasm-0.95.0_win64\ironwail.exe',
]
configs = 'I:\Quake\cfg'
maps = 'I:\Quake\Dev\map'

[cfg_whitelist]
'remobilize.cfg' = ['remobilize_test15']

[jampack]
parents = [
	'readme',
	'sound',
	'gfx/env',
	'music',
	'maps',
	'map',
	'mapsrc',
	'progs',
	'models',
]

[jampack.allowed]
# ex: 'destination folder' = [ 'file1', 'file2', '*.txt ]
# organize these in order, so...
# if you want "readme.txt" to be put inside of the root (/)
# you should have that at the top
'.' = ['descript.ion', 'quake.rc', '*.txt', '*.pak', '*.dat']
'gfx/env' = ['*.tga']
readme = ['*.txt', '*.html', '*.md', 'readme/*']
progs = ['*.mdl']
sound = ['*.wav']
music = ['track*.*']
mapsrc = ['*.map']
maps = ['*.bsp', '*.lit']

[submit]
allowed = [
	'mapsrc/*.map',
	'sound/**/*.wav',
	'music/*',
	'maps/*.bsp',
	'maps/*.lit',
	'gfx/env/**/*.tga',
	'readme/*',
]

[template]
folders = [
	'maps',
	'mapsrc',
	'music',
	'gfx/env/{name}',
	'sound/{name}',
	'progs/{name}',
]

[ericw]
bsp = 'maps'
src = 'mapsrc'

[[ericw.profiles]]
name = 'dev'
qbsp = ['-bsp2', '-verbose']
vis = ['-fast', '-vv']
light = ['-dirtdebug']

[[ericw.profiles]]
name = 'submit'
qbsp = ['-bsp2', '-splitturb']
vis = ['-noambient']
light = ['-extra']
